# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='done_time',
            field=models.CharField(default='', max_length=100, verbose_name='规定完成时间'),
        ),
    ]
