# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_taskmodel_done_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applytaskmodel',
            name='state',
            field=models.CharField(blank=True, choices=[('agree', '同意'), ('not', '不同意'), ('submit', '已提交')], default='submit', max_length=30, null=True, verbose_name='批复状态'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='state',
            field=models.CharField(blank=True, choices=[('accept', '已接受,正在进行中...'), ('done', '已完成'), ('not', '已下发')], default='not', max_length=30, null=True, verbose_name='任务状态'),
        ),
    ]
