# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_remove_applymodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='applymodel',
            name='file',
            field=models.FileField(default=2, max_length=50, upload_to='file/%Y/%m', verbose_name='附件'),
            preserve_default=False,
        ),
    ]
