# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 06:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_applymodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applymodel',
            name='nick_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='申请人'),
        ),
    ]
