# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_auto_20180517_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applymodel',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
    ]
