# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 22:30
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10, verbose_name='部门')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '部门信息',
                'verbose_name': '部门信息',
            },
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.CharField(default='', max_length=20, null=True, verbose_name='出生日期')),
                ('education', models.CharField(default='', max_length=20, null=True, verbose_name='学历')),
                ('major', models.CharField(default='', max_length=20, null=True, verbose_name='专业')),
                ('work_year', models.CharField(default='', max_length=10, null=True, verbose_name='工作年限')),
                ('policital_status', models.CharField(default='', max_length=10, null=True, verbose_name='政治面貌')),
                ('native_place', models.CharField(default='', max_length=50, null=True, verbose_name='籍贯')),
                ('home_address', models.CharField(default='', max_length=50, null=True, verbose_name='家庭住址')),
                ('permanent_address', models.CharField(default='', max_length=11, null=True, verbose_name='户口所在地')),
                ('position', models.CharField(default='', max_length=20, null=True, verbose_name='职位')),
                ('work_num', models.IntegerField(default=0, null=True, verbose_name='工号')),
                ('entry_time', models.CharField(default='', max_length=20, null=True, verbose_name='入职时间')),
                ('entry_year', models.CharField(default='', max_length=5, null=True, verbose_name='本公司入职年限')),
                ('telephone', models.CharField(default='', max_length=12, null=True, verbose_name='座机号码')),
                ('email', models.EmailField(default='', max_length=100, null=True, verbose_name='公司邮箱')),
                ('remarks', models.CharField(default='', max_length=50, null=True, verbose_name='备注')),
                ('base_pay', models.FloatField(default=0, verbose_name='基本工资')),
                ('post_wage', models.FloatField(default=0, verbose_name='岗位')),
                ('bonus', models.FloatField(default=0, verbose_name='绩效奖金')),
                ('benefits', models.FloatField(default=0, verbose_name='保险金(前端四金)')),
                ('mobile_fee', models.FloatField(default=0, verbose_name='通讯费')),
                ('car_fee', models.FloatField(default=0, verbose_name='车费')),
                ('lunch_fee', models.FloatField(default=0, verbose_name='午餐费')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.DivisionModel', verbose_name='所属部门')),
            ],
            options={
                'verbose_name_plural': '员工详细信息',
                'verbose_name': '员工详细信息',
            },
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '员工基本信息', 'verbose_name_plural': '员工基本信息'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nick_name',
            field=models.CharField(default='', max_length=50, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='员工信息'),
        ),
    ]
