# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 00:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180516_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='is_work',
            field=models.CharField(choices=[('job', '在职'), ('quit', '离职')], default='job', max_length=6, verbose_name='是否在职'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='员工姓名'),
        ),
    ]
