# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180517_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='education',
            field=models.CharField(choices=[('college', '大专'), ('undergraduate', '本科'), ('graduate', '研究生'), ('doctor', '博士生')], default='job', max_length=20, verbose_name='学历'),
        ),
    ]
