# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='subject',
            field=models.CharField(default='', max_length=200, verbose_name='类别备注'),
        ),
    ]
